-- CREATE DATABASE
CREATE DATABASE DB_CAKE_SHOP;

-- USE
USE DB_CAKE_SHOP;

CREATE TABLE TB_PREPARADOR (
    ID_PREPARADOR INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE NVARCHAR(50) NOT NULL,
    APELLIDO NVARCHAR(50) NOT NULL,
    DIRECCION NVARCHAR(50),
    TELEFONO NVARCHAR(15),
    ESTATUS NVARCHAR(1) NOT NULL
);

INSERT INTO TB_PREPARADOR (NOMBRE, APELLIDO, DIRECCION, TELEFONO, ESTATUS)
VALUES ('Josue', 'Emilian', 'Guatemala, Guatemala', '2222-2222', 'A');

INSERT INTO TB_PREPARADOR (NOMBRE, APELLIDO, DIRECCION, TELEFONO, ESTATUS)
VALUES ('Valeria', 'Lou', 'Guatemala, Guatemala', '2525-2525', 'A');

CREATE TABLE TB_PASTEL (
    ID_PASTEL INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE NVARCHAR(50) NOT NULL,
    DESCRIPCION NVARCHAR(100),
    ID_PREPARADOR INT,
    FECHA_CREACION DATE,
    FECHA_VENCIMIENTO DATE,
    FOREIGN KEY (ID_PREPARADOR) REFERENCES TB_PREPARADOR(ID_PREPARADOR)
);

INSERT INTO TB_PASTEL (NOMBRE, DESCRIPCION, ID_PREPARADOR, FECHA_CREACION, FECHA_VENCIMIENTO)
VALUES ('Pastel de Chocolate', 'Pastel de chocolate con chispas de chocolate', 1, '2023-01-01', '2023-01-10');

CREATE TABLE TB_INGREDIENTE (
    ID_INGREDIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE NVARCHAR(50) NOT NULL,
    DESCRIPCION NVARCHAR(100),
    FECHA_INGRESO DATE,
    FECHA_VENCIMIENTO DATE
);

INSERT INTO TB_INGREDIENTE (NOMBRE, DESCRIPCION, FECHA_INGRESO, FECHA_VENCIMIENTO)
VALUES ('Harina', 'Harina de trigo', '2023-01-01', '2023-12-31');

CREATE TABLE TB_PASTEL_INGREDIENTE (
    ID_PASTEL_INGREDIENTE INT AUTO_INCREMENT PRIMARY KEY,
    ID_PASTEL INT NOT NULL,
    ID_INGREDIENTE INT NOT NULL,
    FOREIGN KEY (ID_PASTEL) REFERENCES TB_PASTEL(ID_PASTEL),
    FOREIGN KEY (ID_INGREDIENTE) REFERENCES TB_INGREDIENTE(ID_INGREDIENTE),
    CONSTRAINT UC_PASTEL_INGREDIENTE UNIQUE (ID_PASTEL, ID_INGREDIENTE)
);

INSERT INTO TB_PASTEL_INGREDIENTE (ID_PASTEL, ID_INGREDIENTE)
VALUES (1, 1);